name: Alist SDK - Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Install AList
      run: |
        mkdir -p tests/alist
        cd {WORKDIR}/alist
        wget https://github.com/alist-org/alist/releases/download/v3.28.0/alist-linux-amd64.tar.gz
        tar xzvf alist-linux-amd64.tar.gz
        ./alist admin set 123456
        ./alist start

    - name: Run Tests
      run: |
        python -m pytest --log-level=INFO
